name = "DesignModels"
uuid = "a1b99817-8174-466d-8238-ccbc51283cbf"
authors = ["azzaare <jf@baffier.fr> and contributors"]
version = "0.1.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1"
Automa = "^0.8"
JSON3 = "^1.1.1"
