name = "DesignModels"
uuid = "a1b99817-8174-466d-8238-ccbc51283cbf"
authors = ["azzaare <jf@baffier.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
